# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "single" do |h|
    h.vm.network "private_network", ip: "192.168.135.101"
  end
  
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
